### ISSUE TITLE
Is there a way to save the port forwarding rule?

### ISSUE THREAD

**Issue by valkjsaaa** [hronro/iPortForwarder#1]

**Comment by hronro** [comment]
Currently no, but it's on the plan.

**Comment by hronro** [comment]
It is implemented in [308dc54](https://github.com/hronro/iPortForwarder/commit/308dc54c27c3785744057c914e6e93a315f06703).

And you can try it here: https://github.com/hronro/iPortForwarder/actions/runs/5444916046

**Comment by hronro** [comment]
Done in v0.4.0: https://github.com/hronro/iPortForwarder/releases/tag/v0.4.0

**Comment by hronro** [comment]
Now you can save or import a forwarding list from the menu bar (or using <kbd>cmd</kbd>+s and <kbd>cmd</kbd>+o)

<img width="466" alt="CleanShot 2023-07-04 at 15 55 02@2x" src="https://github.com/hronro/iPortForwarder/assets/15059605/2dbf8c89-622a-446e-88a5-bd8f68b39b50">
