### ISSUE TITLE
[Feature Request] Run as a Service and Auto-Start with Configuration

### ISSUE THREAD

**Issue by donnimsipa** [hronro/iPortForwarder#2]
I am highly impressed with this application's capabilities, it's very user-friendly and I use it routinely. However, I find it inconvenient to manually open the app and import the configuration each time, even though I have set it to auto-open at login, it still requires manual configuration import.

If there were a way to make it run as a service and auto-start with a pre-set configuration, it would greatly enhance the app's usability

Looking forward to the possibility of this feature implementation, Thank you

**Comment by hronro** [comment]
After conducting some research, I found that the only way to create a GUI application as a service is through "Login Items," which you have already done (Reference: https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/DesigningDaemons.html).

However, there is one issue you are facing - the app cannot automatically load a saved configuration upon launch. This problem can be easily resolved by adding a new settings window for implementing this feature.

I don't have enough spare time recently to complete this feature, so you may need to wait for a while. If you want to submit a PR, you're more than welcome to do so.

**Comment by hronro** [comment]
Hello @donnimsifa, I have implemented it in the master branch. You can try the pre-built binary from GitHub Actions by clicking here: https://github.com/hronro/iPortForwarder/actions/runs/7524349290 

If everything works well for you, I will release a new version shortly.

**Comment by donnimsipa** [comment]
Hi, @hronro , I apologize I couldn't manage to submit a pull request as my schedule has been quite tight lately.

Anyway, I'm excited to share that I've tested the pre-built binary from the GitHub Actions link you provided (https://github.com/hronro/iPortForwarder/actions/runs/7524349290), and I'm pleased to say it worked seamlessly. The application now effortlessly auto-starts with the pre-set configuration.

Thank you for your hard work and the implementation 😊

**Comment by hronro** [comment]
Great, let's release the new version for this.
