### ISSUE TITLE
Cant't run on MacOS M1 Sonoma because of 

### ISSUE THREAD

**Issue by adacaccia** [hronro/iPortForwarder#3]
Can't run "iiPortForwarder.app” because Apple cannot check presence of malware.
Contact developer :)

**Comment by hronro** [comment]
To bypass this, right-click the app icon and select "Open".

![CleanShot 2024-04-15 at 11 52 08@2x](https://github.com/hronro/iPortForwarder/assets/15059605/50fcc291-2576-4aa5-8152-ec03de1a7937)

Please feel free to reopen the issue if the problem still exists.
