### ISSUE TITLE
I think you should update some modules and stuff !!!

### ISSUE THREAD

**Issue by masoud-mohajeri** [hronro/iPortForwarder#4]
when I try to open it , this error comes : 

“iPortForwarder.app” can’t be opened because Apple cannot check it for malicious software.

This software needs to be updated. Contact the developer for more information.

great job BTW

**Comment by hronro** [comment]
The only reason that this error comes out is that I didn't pay the apple developer fee (99 USD/year) to Apple, which I don't plan to pay in the near future.

A simple way bypass this is: Right click "iPortForwarder.app", choose open.
